### ISSUE TITLE
count data generated from simulate_hierarchicell

### ISSUE THREAD

**Issue by Al-Murphy** [kdzimm/hierarchicell#3]
Hi,

I was wondering about the use of `simulate_hierarchicell()` in 04_compute_error.R script, the simulated data appears to be filtered to only include genes with a mean value above 1:

```
genecounts <- genecounts[which(apply(genecounts, 1, mean) > 5), ]
```

I think this is done to only keep genes which are not differentially expressed between case and controls, is this true? Secondly, does this mean that the converse, genes with a mean value less than or equal to 5, are differentially expressed? I.e:

```
genecounts[which(apply(genecounts, 1, mean) <= 5), ]
```

The documentation for `simulate_hierarchicell()` does not make it clear how differentially expressed genes are identifiable.

Thanks,
Alan.

**Comment by kdzimm** [comment]
Hey Alan,

In the first part the simulated data is filtered to only include genes with a mean value above 5. This is not to only keep genes which are not differentiall expressed. Rather it has more to do with missing values. Genes with low means also will have a ton of missingness which can be problematic for the analysis. 

Per identifying which genes are DE, depending on the FC you specify either all or none should be DE for that particular round of simulation. So, if you specify a FC of 2, all of the genes will have a FC difference of 2, with a random variation pattern that follows real data. Does that help?

**Comment by Al-Murphy** [comment]
Oh okay I think I understand now, so you assume FC>=2 is a differentially expressed gene?

**Comment by kdzimm** [comment]
No, anything with a FC not equal to 1 is assumed to be "DE" with some amount of variance. For example, something can have a FC of 1.1 between groups. It is considered DE because we are drawing from two different distributions (one with a mean of 1x and the other with a mean of 1.1x), once the variance that is typical of real data is added, then we ask: what is the power to actually detect (with statistical significance) a FC of 1.1. Could be 1.3, could be 2.3, or 1.01.

**Comment by Al-Murphy** [comment]
That makes sense, thanks!
