### ISSUE TITLE
Single sample analysis fails - feature request

### ISSUE THREAD

**Issue by daniel-spies** [kdzimm/hierarchicell#4]
thanks for the great tool!

I just realized that if a single sample is analyzed the compute_data_summaries function fails after the uncorrelatedgenes (loop of 1:500) when assigning the rownames to temp.intervar. setting a single value in the 2nd column of the IDs to another value circumvents this issue, but it would be better to account for that in the function.

Also I encounter Errors when running error- or power_hierarchicell whilst the function continues, should I be concerned?

"Error in pwrssUpdate(pp, resp, tol = tolPwrss, GQmat = GQmat, compDev = compDev,  :  Downdated VtV is not positive definite" 

and finally I'd like to request a feature: the results of the error/power function could be returned so that they can be saved, e.g. in my case when I'm testing several foldchanges that I can run the functions in a loop without the need to modify the function itself or capture and dissect the output text.

thanks
daniel

**Comment by kdzimm** [comment]
@daniel-spies Thanks for these comments! I hope the tool has been easy to navigate for you.

Per the issue with "compute_data_summaries" - the "temp.intervar" step is computing the inter-individual variability so you need more than 1 sample to do that. If you have only 1 sample, then you can't estimate the inter-individual variability and you won't be able to estimate power that accounts for the inter-individual variability (which is the key component of this tool). I would recommend just using the default data to estimate parameters for your power calculations if you only have 1 sample.

Per the error. Those errors can happen in scenarios with low sample numbers and low numbers of cells. It means there is complete separation (one group has all positive values while the other has all zeros) and is giving a warning. 

I agree. Thank you so much for this suggestion! We are trying to work out ways like this to improve the calculator, but since I graduated I have not had the time to continue developing this. My previous advisor is hoping to find others to continue developing this tool. There is a lot of room for improvement.

Take care,

Kip
